[versions]
plugin-android = "7.0.3"
plugin-ktlint = "10.1.0"
plugin-maven = "0.18.0"

kotlin = "1.5.31"

ksp = "1.5.31-1.0.0"
caseFormat = "0.2.0"
konsumeXml = "1.0"

appCompat = "1.3.1"
compose = "1.1.0-beta01"
composeActivity = "1.3.1"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "plugin-ktlint" }
plugin-maven = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "plugin-maven" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
caseFormat = { module = "com.fleshgrinder.kotlin:case-format", version.ref = "caseFormat" }
konsumeXml = { module = "com.gitlab.mvysny.konsume-xml:konsume-xml", version.ref = "konsumeXml" }

appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }

[bundles]
plugins = ["plugin-android", "plugin-ktlint", "plugin-maven", "plugin-kotlin", "plugin-ksp"]